### ISSUE TITLE
InteroOpen freezes on Windows

### ISSUE THREAD

**Issue by dwaldhalm** [parsonsmatt/intero-neovim#105]
`:InteroOpen` opens a new split as expected.  It loads the relevant modules and leaves me with a ghci-looking prompt. 
After setting focus on the repl split and typing `a` or `i` (hoping to enter text into the repl), Neovim command line says "-- TERMINAL --" and then freezes.

**Comment by parsonsmatt** [comment]
That's weird. Does a normal `:terminal` window work on your system? What version of neovim are you running?

**Comment by dwaldhalm** [comment]
`nvim --version`
NVIM v0.2.1-25-g2e3b78d1

No, `:terminal` doesn't work.  It behaves as I described.

**Comment by parsonsmatt** [comment]
`intero-neovim` depends on Neovim's terminal support. If plain `:terminal` fails, then you'll want to file an issue with the neovim repository.

I'm going to close this issue as out-of-scope. When you get `:terminal` working, feel free to re-open if the problem still exists.

Thanks for reporting!
