### ISSUE TITLE
Breaks local configs via vim-localvimrc

### ISSUE THREAD

**Issue by kozross** [parsonsmatt/intero-neovim#107]
If I have this installed, and attempt to open a Haskell source file in a directory with a ``.lvimrc``, the load of that file (or rather, the dialog asking me if I want it loaded) will be skipped. ``vim-localvimrc`` can be found [here][1].

[1]: https://github.com/embear/vim-localvimrc

**Comment by parsonsmatt** [comment]
That's very strange. Can you post a minimal `init.vim` that replicates this behavior?

**Comment by kozross** [comment]
Seems like the error was mine - I can do this with built-in Neovim behaviour via ``.nvimrc`` files instead of this package, and not get any issues.
