### ISSUE TITLE
Investigate a pure GHCi backend

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/intero-neovim#108]
GHCi as of 8.0.2 supports `:type-at` and `:loc-at` commands, just like Intero. These are the killer features that Intero brought to GHCi. The project [`neovim-ghci`](https://github.com/owickstrom/neovim-ghci) is a fork of this one that uses GHCi instead of `intero`.

`intero` imposes some additional complexity cost: checking if it is installed, spending some time building it, requiring a `stack` project, etc. and using GHCi entirely would eliminate this complexity.

We should be able to support GHCi and Intero by allowing a configuration switch, or (if Intero brings nothing extra to the table) drop it in favor of GHCi. At which point the plugin's name becomes a little misleading :smile:

**Comment by owickstrom** [comment]
As you know, I'm in favour of merging the projects (whatever that means, practically). Now that have most loose ends done in neovim-ghci, I can create some PRs here instead, and we can phase my fork out. If you want to use that name here instead, we can do that?

**Comment by rdnetto** [comment]
I suggest we start by switching between them based on configuration / GHC version. GHC 8.0.2 is still new enough that I imagine a significant number of our users are on 7.x. (The LTS release of 8.2 might be a good time to revisit this.)

**Comment by owickstrom** [comment]
I've started on an implementation for this. I'm thinking we should keep all the behavior as default, and with a configuration switch enable "any GHCi". As a start, maybe disable the Stack/Intero-specific features in that mode, e.g. settings targets and passing specific options. Then if you override with another GHCi, you have to set your targets and other flags in the overriding command, as in neovim-ghci: https://github.com/owickstrom/neovim-ghci#using-the-stack-repl

What do you think? We could maybe re-enable those features with some detection later if it makes sense, but as a starting point, if you disable regular Intero mode, you're more on your own.

**Comment by parsonsmatt** [comment]
@rdnetto Surprisingly enough, most people upgrade GHC rather quickly: http://taylor.fausak.me/2017/11/15/2017-state-of-haskell-survey-results/#question-18 

@owickstrom I like that plan. In the future, we may want to create a new GitHub organization and repository when the plugin is GHCi-backend-agnostic, and point users of `intero-neovim` to that instead. The existing [neovimhaskell](https://github.com/neovimhaskell) group might be a good place to put the project -- I'd want to name it in a way that doesn't privilege the backend as `neovim-ghci` and `intero-neovim` do.

**Comment by owickstrom** [comment]
@parsonsmatt Yeah, that sounds good. I thought about naming a bit as well, and maybe something reflecting what the plugin is about, rather than how it works, would be more flexible and useful. Random ideas are "interactive-haskell-neovim", "haskell-neovim", or something more innovative, e.g. HaskForce and Leksah.

**Comment by owickstrom** [comment]
Want to close this now when #119 is merged? Or should we keep it open to discuss name changes/moves?

**Comment by parsonsmatt** [comment]
@owickstrom Let's close this out. I'll create another issue for naming.
