### ISSUE TITLE
Getting error for invalid Hlint path

### ISSUE THREAD

**Issue by lsund** [parsonsmatt/intero-neovim#113]
intero-neovim gives me the following message:

`Dummy|| ~/.stack/snapshots/x86_64-linux-nopie/lts-8.23/8.0.2/share/x86_64-linux-ghc-8.0.2/hlint-1.9.41/HLint.hs: openFile: does not exist (No such file or directory)`

My actual path on my machine starts with ` ~/.stack/snapshots/x86_64-linux-tinfo6-nopie/` so that's why I'm getting this error. How I fix it?
**What i tried**
* reinstalled hlint
* stack update

**Speccs:**
arch linux 4.13
hlint 2.0.9
nvim 0.2.2
stack 1.6.0

**Comment by parsonsmatt** [comment]
Can you post exactly what you're doing that causes the error? I'm unclear when or how this occurs.

**Comment by lsund** [comment]
It happened on the second InteroReload after an error was found. Error dissapeared after upgrading hlint to 2.0.10. Sorry about this thought I upgraded earlier but turned out I was still on a lower version.
