### ISSUE TITLE
`InteroGoTo` does not add to `jumplist`

### ISSUE THREAD

**Issue by stellarhoof** [parsonsmatt/intero-neovim#123]
Invoking `InteroGoTo` and subsequently doing `<C-O>` doesn't return to the previous location

**Comment by stellarhoof** [comment]
I need to further test this. It does seem to work now

**Comment by zong-nec** [comment]
FYI there's another issue about the same topic at #55 .

**Comment by parsonsmatt** [comment]
I am going to close this. If you see this again, please reopen :)
