### ISSUE TITLE
Consider using `vimdoc` for helpfile generation

### ISSUE THREAD

**Issue by stellarhoof** [parsonsmatt/intero-neovim#128]
How do you generate your helpfile? Manually? Do you use a tool? I'm thinking of submitting a pull request but I don't want to manually meddle with helpfiles.

**Comment by parsonsmatt** [comment]
I have been manually editing the help docs. Do you have a workflow suggestion? I am a vim noob and would definitely appreciate anything that makes the project nicer :smile:

**Comment by stellarhoof** [comment]
There is https://github.com/google/vimdoc, probably better maintained than https://github.com/wincent/docvim. I tried to install that last one but it doesn't build with GHC `8.0.2`. I wouldn't mind making a pull request to migrate to `vimdoc`. It seems pretty nice.

**Comment by parsonsmatt** [comment]
`docvim` uses Markdown which is nice but not building at all is kind of a problem :\

**Comment by stellarhoof** [comment]
If you're looking for writing in `md`, there's also `https://github.com/xolox/vim-tools`. I prefer `vimdoc` because it's less cognitive load: write comments, get documentation, which also encourages having well documented source.

**Comment by parsonsmatt** [comment]
I'm happy for anything that's an improvement :smile:
