### ISSUE TITLE
Command to insert the type of a value into the source

### ISSUE THREAD

**Issue by expipiplus1** [parsonsmatt/intero-neovim#14]
ghc-mod-vim has a very useful feature to query the type of the value under the cursor and insert this type into the source on the preceding line at the same indentation.

A basic version of this could ignore the indentation as this is usually used on top level definitions.

An example would be

```haskell
foo = ()
```

With the cursor somewhere over `foo` running `InteroInsertType` would change to source to

```haskell
foo :: ()
foo = ()
```

**Comment by parsonsmatt** [comment]
This should be easy -- the two type functions in the plugin already retrieves the identifier and kicks off a callback that will echo the type. The type insert function would follow nearly the same logic, but instead of echoing, would paste it in the line above.

**Comment by parsonsmatt** [comment]
This has been implemented! It's not super smart right now -- it inserts it at the top level. I will probably want to copy over the `ghcmod-vim` type region code at some point, which has the info on where the type should be inserted.

**Comment by expipiplus1** [comment]
cool, Thanks!
