### ISSUE TITLE
Intero Not Loading Properly

### ISSUE THREAD

**Issue by StevenXL** [parsonsmatt/intero-neovim#143]
Hi Everyone, 

I'm not sure if this is the correct place to post this, because I do not think this is a problem with `intero-neovim` itself. I think it's a problem with my configuration. 

Anyway, when I type `:InteroOpen` in `vim`, I don't get any errors. 

However, if I navigate to an identifier and type in `:InteroGenericType`, I get this error:

```
Error detected while processing function intero#repl#type[4]..intero#repl#type_at[18]..<SNR>161_ghci_supports_type_at_and_uses:

line    1:
E121: Undefined variable: g:intero_backend_info
E116: Invalid arguments for function intero#process#backend_info#version_gte
E15: Invalid expression: intero#process#backend_info#version_gte( g:intero_backend_info.version, [8, 0, 1])
```

And if I type `:InteroLoadCurrentFile`, I get this error:

```
Error detected while processing function intero#repl#load_current_file:
line    2:
Intero is still starting up
```

The problems seem to be obvious from the error messages, but I am confused as to why I am getting those problems in the first place. I don't know why there is no back-end info, as I have not set that explicitly and expected it to default. And I certainly don't know why it is taking so long to start up. Might these error messages be red herrings?

**Comment by parsonsmatt** [comment]
Do you have a custom prompt?

**Comment by StevenXL** [comment]
@parsonsmatt I *did*. It works now. No one needs that little `λ` anyway. ;). Thank you.

**Comment by parsonsmatt** [comment]
dang custom prompt strike again!!!
