### ISSUE TITLE
`InteroGoToDef` does not reliably add to vim's jump list

### ISSUE THREAD

**Issue by bradlarsen** [parsonsmatt/intero-neovim#157]
Observed behavior: The `InteroGoToDef` command doesn't reliably adjust vim's jump list.  This makes it difficult to return to where you were after you use `InterGoToDef` — normally you'd use C-o to jump back, but this doesn't work if you already have the jumped-to file open.

Desired behavior: C-o and C-i work as expected to jump back to where you originally were, and back again to the place `InteroGoToDef` caused you to go.

I see the current behavior because in autoload/intero/loc.vim, the `s:handle_loc` function uses the vimscript `cursor` builtin to jump to the definition, and `cursor` explicitly does not touch vim's jump list (which is what underlies the C-o and C-i commands).

See `:help cursor` in vim, and also https://stackoverflow.com/questions/19195160/push-a-location-to-the-jumplist.

**Comment by parsonsmatt** [comment]
Closed by #158 

Thanks for the PR :)
