### ISSUE TITLE
Is the stack dependency necessary

### ISSUE THREAD

**Issue by expipiplus1** [parsonsmatt/intero-neovim#19]
Is it sensible to support the use case of running intero without Stack?

**Comment by expipiplus1** [comment]
At the least, if `stack` can't be found that should be in the error message produced by `intero#process#ensure_installed()`

**Comment by parsonsmatt** [comment]
I'm going to say yes. Here's [Chris Done's](https://www.reddit.com/r/haskell/comments/4x6n2y/intero_for_emacs_complete_interactive_development/d6d0rg0?context=1) reasoning for keeping it `stack` only.

I'll include a check for `stack` presence and display an error message if it's not available.

**Comment by parsonsmatt** [comment]
Stack notice implemented in `v1.0.1`
