### ISSUE TITLE
`timer_start` not found with neovim 0.1.3

### ISSUE THREAD

**Issue by expipiplus1** [parsonsmatt/intero-neovim#20]
Trying to use intero-neovim with neovim v0.1.3 fails with this message:

```
Error detected while processing function intero#process#start[4]..<SNR>97_start_buffer:
line   12:
E117: Unknown function: timer_start
```

Could intero-neovim check the vim version to ensure compatibility?

**Comment by expipiplus1** [comment]
likewise with 0.1.4

**Comment by parsonsmatt** [comment]
Thanks for reporting! I'll get that notice in soon.

**Comment by expipiplus1** [comment]
@parsonsmatt what version of neovim are you using with intero.

I'm using 006f9c0 and intero seems to be opening up loads of splits until I kill the process when I run `InteroInfo`

**Comment by parsonsmatt** [comment]
NVIM 0.1.5-dev is what I've got now.

**Comment by expipiplus1** [comment]
I think that's a running version number. Do you know more precisely?

**Comment by parsonsmatt** [comment]
It requires  `patch-7.4.1578`, which I'm now checking for and failing to load the plugin otherwise.

With any luck I'll be able to remove that dependency soon :smile:
