### ISSUE TITLE
intero#util#path_to_module assumptions on code layout

### ISSUE THREAD

**Issue by simonyangme** [parsonsmatt/intero-neovim#22]
It looks like `intero#util#path_to_module` assumes first directory can be dropped, when default Yesod template doesn't follow that pattern (where code tends to go into src dir at project root).

Any reason why detect_module here isn't being used instead? https://github.com/parsonsmatt/intero-neovim/blob/master/autoload/intero.vim#L62-L76

**Comment by parsonsmatt** [comment]
Fixed in #23
