### ISSUE TITLE
`stack build intero` should be performed asynchronously

### ISSUE THREAD

**Issue by rdnetto** [parsonsmatt/intero-neovim#28]
This is currently executed automatically when opening a Haskell file if intero has not been compiled for that resolver before, and will take several seconds in the best case where its dependencies are already compiled. This blocks the UI.

This is particularly bad if you run `nvim-qt Main.hs`, since the GUI will be unable to connect to Neovim until compilation is finished, and actually times out.

**Comment by parsonsmatt** [comment]
Great call. My intent was to mimic the behavior of the emacs plugin.

I suppose we could have a local variable to indicate whether or not intero was loaded/installed/ready to go, and block any intero-specific functions from being used until that was fulfilled.
