### ISSUE TITLE
Need to set working directory before invoking stack

### ISSUE THREAD

**Issue by rdnetto** [parsonsmatt/intero-neovim#29]
Intero-neovim does not set the working directory before invoking Stack. This means that `stack build intero` and `stack ghci --with-ghc=intero` run with the default working directory (usually $HOME), instead of a path inside the Stack project, which means they run with a different resolver/GHC.

This also means that the REPL will fail to load the project's files.

### Steps to reproduce:
* open Neovim (working directory defaults to $HOME)
* run `:e my-haskell-project/src/Main.hs`
* switch to REPL and run:
```
:l Main                                  -- this fails
:m +System.Directory
getCurrentDirectory             -- returns $HOME
```

### Fix
Setting the working directory to the directory containing the file doesn't seem to be a complete fix, because the REPL will still fail to load the files. The simplest solution would be to invoke [rooter](https://github.com/airblade/vim-rooter) before invoking stack [here](https://github.com/parsonsmatt/intero-neovim/blob/master/autoload/intero/process.vim#L18), but that means adding another plugin as a dependency, and also assumes that the user is either using VCS or has configured rooter to recognize `stack.yaml` as marking a project root.

The best (though most involved) approach may be to manually search for the directory containing `stack.yaml`. This has the additional benefit that it would also be easy to let the user specify an alternative filename for it.

I'm happy to raise a PR for this, just wanted to get your opinion on which solution you'd prefer first.

**Comment by ChrisPenner** [comment]
I've been having some issues loading modules in a stack project with multiple packages; The [Rasa Project](https://github.com/chrispenner/rasa) to be specific; There's a single stack.yaml at the root of the project with files for each package. Any chance that this could help with that?

I also use `set autochdir` in my Vimrc; so it would be great if the solution for this kept that in mind as well. Right now I'm getting errors like the following (even after explicitly loading the module) 

```No module info for the current file! Try loading it?```

If I disable `autochdir` and restart nvim I get errors like:

```target ‘rasa-ext-views.src.Rasa.Ext.Views’ is not a module name or a source file```

Thanks for taking a look at this! This is a great tool!

**Comment by parsonsmatt** [comment]
Sorry I'm taking so long to respond to this! This is a fantastic find, thanks for bringing it up.

This is a little complicated, as I don't typically like it when processes/plugins reset my CWD, and I would not want this plugin to do that. If I have a project like

```
foo
 |-- bar/
 +-- baz/
```

I'd frequently open vim in `baz`, expecting that as cwd for further shell commands. So the solution I'd want to implement, I think, is to have a (buffer?) local variable `intero_working_directory` that is determined by walking up the directory tree until we find a stack.yaml. If we don't find one, then we assume we're in the global stack project.

**Comment by rdnetto** [comment]
> This is a little complicated, as I don't typically like it when processes/plugins reset my CWD, and I would not want this plugin to do that.

>  So the solution I'd want to implement, I think, is to have a (buffer?) local variable intero_working_directory that is determined by walking up the directory tree until we find a stack.yaml. If we don't find one, then we assume we're in the global stack project.

Agreed. I don't think it should be buffer local though, since we only spawn one Intero session when opening multiple Haskell files, by default.

Also, instead of storing the working directory, it might make more sense to store the path to the `stack.yaml` instead. A quick test indicates that Stack implicitly sets the root directory when this option is specified. We could even go a step further and just use the `STACK_YAML` environment variable instead of defining a variable in Vim, though that has the slightly annoying side-effect of displaying a warning `Getting project config file from STACK_YAML environment` on every Stack command.

**Comment by ChrisPenner** [comment]
Seems to be working better for me! I'll let you know if I find any issues! Thanks!
