### ISSUE TITLE
Ability to specify targets

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/intero-neovim#37]
A user should be able to specify targets of the given stack.yaml that should be loaded.

The emacs version calls `stack ide targets` and uses that as the list of available targets.

It would be cool to present a selection buffer of possible targets and allow the user to choose which ones they wanted. I'll have to figure out how that works.

**Comment by owickstrom** [comment]
A first version of this could perhaps be an alternate command, say `:InteroStartTargets`, taking arguments and passing them to the Stack GHCi invocation? A bit rough, but something to start with at least. What do you think?

**Comment by parsonsmatt** [comment]
That sounds promising. I actually need this to use the plugin on $job's Haskell project, so I might investigate this in the next few days.

**Comment by parsonsmatt** [comment]
Right now, we have `intero#util#stack_opts()` which returns the options to pass to the call. It's implemented as:

```viml
" autoload/intero/util.vim
function! intero#util#stack_opts() abort
    return '--stack-yaml ' . g:intero_stack_yaml
endfunction

"autoload/intero/process.vim
" ...
    call termopen('stack ' . intero#util#stack_opts() . ' ghci --with-ghc intero', {
                \ 'on_stdout': function('s:on_stdout'),
                \ 'cwd': pyeval('intero.stack_dirname()')
                \ })
" ...
```

The targets we want to load would need to be passed here. So `stack_opts` could return this. Having `g:intero_load_targets` seems like a sensible option, with `StartInteroWith` accepting a target, possibly validated against `stack ide targets`.

**Comment by owickstrom** [comment]
Yeah, same here, I would love to have this at work for remote pair programming sessions.

OK, you mean `g:intero_load_targets` would be a variable that is mutated when `StartInteroWith` is invoked? My vimscript skills are weak, but I might be able to piece that together into a PR. :)

**Comment by parsonsmatt** [comment]
I have a basic implementation up here: https://github.com/parsonsmatt/intero-neovim/pull/51

I *really* want it to be able to select from a list, but `inputlist` only allows a single selection :(

**Comment by owickstrom** [comment]
Cool. I tried it but didn't really understand the multiple selection buffer thing, if it had any effect. Then I had the whole thing stuck on "Intero still compiling", but that seems unrelated. Anyway, glad to test again once you're happy with the PR. For my purposes, having to write out the targets in the start command is OK.

**Comment by owickstrom** [comment]
Got back to trying intero-neovim now, and this worked very well. Thanks!
