### ISSUE TITLE
InteroTypeInsert fails with excess text

### ISSUE THREAD

**Issue by wbthomason** [parsonsmatt/intero-neovim#39]
**Expected behavior:** Upon running `:InteroTypeInsert`, the type of the object under the cursor is inserted on the line above.
**Actual behavior:** A string containing the type of the object under the cursor is inserted in the correct location, but this string also contains ASCII control characters (`^@`) and the list of loaded modules.

I suspect that this is due to a change in the output of Intero (I'm using Intero 0.1.20 with GHC 8.0.2). It looks like `s:paste_type` (https://github.com/parsonsmatt/intero-neovim/blob/da0e8684ea30943949d4cc3fdb04da987a70f578/autoload/intero/repl.vim#L85) just pastes the entire last output of Intero, which may no longer be the correct behavior. 

I can try to put together a PR myself for this, but I'm not very experienced with vimscript and don't know the gitflow model, so it might take some time.

**Comment by wbthomason** [comment]
Additionally, if I run `:InteroTypeInsert` right after Intero first loads, I get the dump of all of Intero's startup logging in the inserted type. This seems to be the same issue.

**Comment by mixmaster** [comment]
I met the same issue. It is partially caused by a bug in the function intero#util#path_to_module(). I've created a pull request to fix it.

Even with the fix, you would still need to firstly load your module (:InteroLoadCurrentModule) before :InteroTypeInsert can correctly function.

**Comment by rdnetto** [comment]
I'm working on this and should have a fix up soon.
