### ISSUE TITLE
Using `:set -fobject-code` with intero-neovim

### ISSUE THREAD

**Issue by lwm** [parsonsmatt/intero-neovim#41]
When I run `stack ghci` and I `:set -fobject-code`, I get one full build and then incremental compiling afterwards (mega time saver). Trouble is, after I've done that first build and then I start neovim, intero starts another build again.  How can I get intero-neovim to know that I have `:set -fobject-code` and it should only incrementally build?

**Comment by parsonsmatt** [comment]
Intero needs to do an initial build anyway for itself IIRC, and it doesn't take advantage of previous builds by stack ghci or similar. You can do `:set -fobject-code` in the Intero REPL that's used by neovim.

**Comment by lwm** [comment]
> You can do :set -fobject-code in the Intero REPL that's used by neovim.

Could we add something to automatically pick up that option? I saw that `stack ghci --with-ghc intero --ghci-options="-fobject-code"` works. Could we set neovim config to thread through the options?

**Comment by parsonsmatt** [comment]
I recall that flag breaking a project with a lot of Template Haskell so I'm reluctant to turn it on for all projects by default. Making it a user configurable option would be sensible though.

**Comment by lwm** [comment]
> Making it a user configurable option would be sensible though.

OK, I'll try and submit a patch if no one gets to it first :+1:

**Comment by parsonsmatt** [comment]
This one should be fairly easy to accomplish :smile: The function that opens the buffer is in `autoload/intero/process.vim` called `s:start_buffer`. Currently it calls `intero#util#stack_build_opts()` which returns the load targets. We can enable this by checking for a `g:intero_ghci_options` and appending `'--ghci-options="' . g:intero_ghci_options . '"'` to that.

**Comment by lwm** [comment]
Hackity hack hack hack (I have no idea what a Vim script is, so it's not 'friendly' :))
