### ISSUE TITLE
Open intero terminal buffer in vertical split?

### ISSUE THREAD

**Issue by lwm** [parsonsmatt/intero-neovim#42]
I was [poking around](https://github.com/parsonsmatt/intero-neovim/blob/master/autoload/intero/process.vim#L181) there and saw that it is hard coded to be a small horizontal split. It'd also be nice to have a vertical split, for example, when a long GHC error message needs to be inspected.

I can open up my own terminal buffer but then the `buffer_id` is not rigged up.

**Comment by parsonsmatt** [comment]
I believe you should be able to do ordinary buffer/pane movements for the terminal. `<Ctrl>-w[H,J,K,L]` will make it take up the top/bottom/left/right half of the screen.

**Comment by lwm** [comment]
Ah yes, that's great, thanks!!!
