### ISSUE TITLE
pyeval-related errors

### ISSUE THREAD

**Issue by wbthomason** [parsonsmatt/intero-neovim#45]
Whenever a Haskell file is opened with intero-neovim loaded, a large number of errors are produced (actually, all the same error, repeated). The messages indicate that the `pyeval` call to run `strip_ansi` fails because the `vim` object (used/introduced here: https://github.com/parsonsmatt/intero-neovim/commit/9844b3cfe9629317112fde07fb5a530d7cc48873#diff-d52c00b16d1986fbb856e76f08d27910R183) cannot be found. Looking at the Python 2 Neovim client (https://github.com/neovim/python-client/blob/4dbfbd11a28b765a54928ebe6c6173c336ed841e/neovim/plugin/script_host.py), it's not clear where the `vim` object is expected to have been defined.

I'm not knowledgeable enough about the legacy Python interface in Vim to know if this is a bug in this plugin (i.e. if it's not correct to use the `vim` object without initializing it) or with Neovim (i.e. if the Python 2 Neovim client should initialize and provide access to the `vim` object). I'll try to dig deeper in debugging when I have more time.

For debugging purposes, I'm on Arch Linux with Neovim 0.2.0 and the latest Python 2 Neovim client.

**Comment by rdnetto** [comment]
This was introduced by #44. It looks like I didn't catch it in local testing because I have other plugins which import it, and everything uses the same Python process.

**Comment by rdnetto** [comment]
I've pushed a fix to master - please pull it and let me know if the problem persists.

**Comment by wbthomason** [comment]
This appears fixed. Thank you!
