### ISSUE TITLE
write_update causes nonexistent file error

### ISSUE THREAD

**Issue by wbthomason** [parsonsmatt/intero-neovim#47]
When `write_update` is called (https://github.com/parsonsmatt/intero-neovim/blob/080d43eb3328c331dabe2c40493e4755716bb66b/autoload/intero/maker.vim#L19), I get an error about `.stack-work/logs/intero-build.log` not existing and thus not being openable for writing. This seems tied to the Neomake maker (I am not using Neomake), but it is called in several places. This probably happens because the `.stack-work/logs` directory does not exist. I'm using latest `stack` (1.4.0), and have confirmed that this directory is not created after a clean build, etc. Is the intent that `stack` or `intero-neovim` creates this directory? It's entirely possible that this isn't actually a bug and I've just missed some configuration step on my end.

**Comment by rdnetto** [comment]
This almost certainly a bug on my part - the Neomake-integration code assumes that the directory exists without creating it. I thought that Stack would create it when compiling anything, but it appears that if all the dependencies have been compiled before (and cached in `~/.stack`) then it isn't created. It should be pretty trivial to fix.

**Comment by wbthomason** [comment]
Thanks! Can confirm that this is fixed for me.
