### ISSUE TITLE
InteroHide seems to have stopped working

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/intero-neovim#56]
Expected behavior: InteroClose closes the Intero repl

Actual behavior:  InteroClose doesn't do anything

tested on master branch

**Comment by jez** [comment]
Odd; I confirm this as well. One quick workaround that seems to work is using `:InteroKill`, which correctly closes the buffer in addition to shutting down the background process.

**Comment by jez** [comment]
I bet this is due to the recent changes in #50 relating to initialization.

**Comment by parsonsmatt** [comment]
I've fixed this in #57 :smile:
