### ISSUE TITLE
Intero `:reload` fails if anything was entered into the REPL

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/intero-neovim#66]
To reproduce:

1. Boot intero
2. Open the REPL and type `print`
3. Reload Intero

It will try to run `print:reload`

To fix: clear the REPL before sending the reload

**Comment by jez** [comment]
I was having a similar issue. My issue was because I have Vim keybindings in my inputrc, which I think GHCi picks up on. If I went into readline normal mode, left the terminal buffer, then ran something like :InteroReload, it would fail. 

Do you use Vim keybindings with GHCi/readline?

**Comment by jez** [comment]
Oh never mind, I misinterpreted your issue!
