### ISSUE TITLE
Neomake integration is borked - not showing anything

### ISSUE THREAD

**Issue by lwm** [parsonsmatt/intero-neovim#74]
It doesn't seem to work any more. Possibly related to https://github.com/parsonsmatt/intero-neovim/issues/68 because I can only see the errors when I run `:InteroOpen`.

**Comment by lwm** [comment]
@rdnetto, I have a REPL open and loaded and ran `:InteroInfo` and got:

```
Error detected while processing function intero#repl#info:                                                                                                                
line    2:                                                                                                                                                                
Intero is still starting up
```

See:

![image](https://user-images.githubusercontent.com/1991377/28754020-58d031fa-753d-11e7-8a32-ad9a30965d2a.png)

**Comment by adelbertc** [comment]
I am observing this as well. Updated the plugin this morning.

**Comment by lwm** [comment]
Following on from #69, I tried to run `:InteroLoadCurrentModule` and got:

```
 3 Intero                                                                           
Error detected while processing function intero#repl#load_current_file:             
line    2:                                                                          
Intero is still starting up                                                         
Press ENTER or type command to continue  
```

**Comment by rdnetto** [comment]
Awesome, that confirms my theory - intero-neovim isn't recognizing the prompt.

Can one of you checkout the `debugging_prompt_parsing` branch and tell me what error message is displayed when Intero is starting? Intero's output would also be helpful.

**Comment by lwm** [comment]
After switching over to that branch and running `:InteroLoadCurrentModule`, I got:

```
Error detected while processing function intero#repl#load_current_file:                                                                                                   
line    1:                                                                                                                                                                
E121: Undefined variable: g:intero_started                                                                                                                                
E15: Invalid expression: !g:intero_started
```

Running `:InteroOpen` doesn't return any errors (REPL comes up), but running `:InteroReload` gives:

```
Error detected while processing function intero#repl#reload:                                                                                                              
line    2:                                                                                                                                                                
Intero is still starting up  
```

Not sure how to give more debugging information (any tips!?).

**Comment by adelbertc** [comment]
@rdnetto While this is happening would you mind reverting/un-doing these debugging changes and move them to another branch? At least vim-plug [does not seem to allow you](https://github.com/junegunn/vim-plug/issues/26#issuecomment-46777159) to pin a plugin on a hash, only versions, and right now it seems like `master` is broken?

**Comment by lwm** [comment]
@albertc you can simply jump jnto ~/.config/nvim/plugged/intero-neovimand git checkout yourself

**Comment by rdnetto** [comment]
*facepalm* I should have looked at the screenshot more closely - @lwm you're using a custom prompt which doesn't contain `>`, which is why the regex isn't matching. Can you try setting [`g:intero_prompt_regex`](https://github.com/parsonsmatt/intero-neovim/blob/master/doc/intero.txt#L269) (replace the > with lambda) and see if that fixes the problem?

@adelbertc @eugleo Are you also using custom prompts?

**Comment by Eugleo** [comment]
@rdnetto Yes, I am. Will try once I return home.

**Comment by lwm** [comment]
> @lwm you're using a custom prompt which doesn't contain >, which is why the regex isn't matching.

Ahhh, right.

I have the following set in my `.ghci` file:

``` haskell
:set prompt "\x03BB "
```

And so, I tried the following settings:

``` vim
let g:intero_prompt_regex="'[^-]\x03BB'"
```
And:

```
let g:intero_prompt_regex="'[^-]λ'"
```

And on the master branch (after a fresh `git pull`) and the debugging_prompt_parsing branch.

No dice.

**Comment by Eugleo** [comment]
@rdnetto Well, once I edited the regex, it works! Great, thanks for help.

**Comment by lwm** [comment]
@Eugleo, could you pass me a diff of your changes? I'm probably just doing it wrong ...

**Comment by Eugleo** [comment]
@lwm I’m not at my Mac right now, but I’ll try to guess.

My ‘.ghci’ file sets the prompt to ‘ΣΠ: ‘ (notice the space at the end). And the regex setting in my ‘init.vim’ is ‘let g:intero_prompt_regex=“[^-]: “‘ (notice the space here again). And it works.

**Comment by lwm** [comment]
Thanks @Eugleo! Closing this one off then :beers:
