### ISSUE TITLE
Include command :InteroInfoPreview

### ISSUE THREAD

**Issue by unode** [parsonsmatt/intero-neovim#81]
Tried it today and I'm already sold. Intero is great for larger projects where using ghcmod-vim is just too slow.

The only feature I currently miss is something equivalent to `:GhcModInfoPreview` which is equivalent to `:InteroInfo` but the output is accumulated on a split buffer so you can visually compare types.

There's also the added bonus that syntax highlight can be enabled on this buffer.

**Comment by parsonsmatt** [comment]
I'm curious if opening the REPL handles this use case?

Here's the output I have after opening the REPL and running `InteroInfo` on two terms:

![image](https://user-images.githubusercontent.com/7310112/33351789-bcf3854a-d462-11e7-8a88-6c99b13e1328.png)

**Comment by unode** [comment]
I guess that works indeed. Not quite the same but close enough.

Thanks
