### ISSUE TITLE
Neomake integration seems borked

### ISSUE THREAD

**Issue by lwm** [parsonsmatt/intero-neovim#86]
I only get a marker in the gutter with an 'x' and no quick list of errors pops up, as is normally reported from Neomake. This is with the latest intero-neovim and latest Neomake. Anyone else seen this?

Here's a screen grab:
![image](https://user-images.githubusercontent.com/1991377/29939479-4a204f06-8e8c-11e7-845a-1a703f49e985.png)

**Comment by rdnetto** [comment]
I can't reproduce this with the latest intero-neovim + neomake. Things to check:
* is `g:intero_started` set to true? (should be, if we're populating the gutter)
* if you run `:copen`, does is the quickfix list populated?
* does running `:InteroReload` fix it?

**Comment by lwm** [comment]
Ah, it was something in my setup. Thanks for testing and the hints, much appreciated!
