### ISSUE TITLE
Not handling Neomake multiple makers?

### ISSUE THREAD

**Issue by decentral1se** [parsonsmatt/intero-neovim#99]
When I have a hlint maker and am using intero-neovim, if I get errors from both plugins, they go into two different pop up lists instead of the same one - this means half the screen gets taken over by it. Is there something we can do about this? Anyone seen that?

**Comment by jez** [comment]
For what it’s worth, I disable Intero warnings with Neomake and use ALE
exclusively for all warnings (including hlint and GHC errors).

If you want to try this out you can see it in my dotfiles:

https://github.com/jez/dotfiles/blob/master/vim/plug-settings.vim#L431
https://github.com/jez/dotfiles/blob/master/vim/plug-settings.vim#L257

Though it does mean I have to

stack build ghc-mod

in every project that I want to see GHC build errors and warnings.

**Comment by rdnetto** [comment]
This is probably happening because Intero is populating the quickfix list (errors for the entire project), and hlint is populating the location list (errors for a single file). It might make sense to try to fix this in Neomake, by adding a flag to append all errors to the quickfix list.

**Comment by parsonsmatt** [comment]
It's surprising that it makes two different lists for this, since it's neomake under the hood. Do other plugins have this issue?
